<?php

namespace ContainerDU20yoV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlattenExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YpWbaTu.Symfony\Component\ErrorHandler\Exception\FlattenException' shared service.
     *
     * @return \Symfony\Component\ErrorHandler\Exception\FlattenException
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YpWbaTu": it references class "Symfony\\Component\\ErrorHandler\\Exception\\FlattenException" but no such service exists.');
    }
}
