<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6HNwruA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6HNwruA/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container6HNwruA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container6HNwruA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container6HNwruA\App_KernelProdContainer([
    'container.build_hash' => '6HNwruA',
    'container.build_id' => '04311c2e',
    'container.build_time' => 1624262848,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6HNwruA');
