<?php

namespace ContainerLbk3N42;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YpWbaTuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YpWbaTu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YpWbaTu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exception' => ['privates', '.errored..service_locator.YpWbaTu.Symfony\\Component\\ErrorHandler\\Exception\\FlattenException', NULL, 'Cannot autowire service ".service_locator.YpWbaTu": it references class "Symfony\\Component\\ErrorHandler\\Exception\\FlattenException" but no such service exists.'],
        ], [
            'exception' => 'Symfony\\Component\\ErrorHandler\\Exception\\FlattenException',
        ]);
    }
}
