<?php

namespace ContainerLbk3N42;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qci20iR.Symfony\Component\Security\Core\Exception\AccessDeniedException' shared service.
     *
     * @return \Symfony\Component\Security\Core\Exception\AccessDeniedException
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qci20iR": it references class "Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException" but no such service exists.');
    }
}
