<?php

namespace Container6HNwruA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Security\AccessDeniedHandler' shared autowired service.
     *
     * @return \App\Security\AccessDeniedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Security\\AccessDeniedHandler'] = $instance = new \App\Security\AccessDeniedHandler();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Security\\AccessDeniedHandler', $container));

        return $instance;
    }
}
