<?php

namespace Container6HNwruA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDistributeurRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DistributeurRepository' shared autowired service.
     *
     * @return \App\Repository\DistributeurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DistributeurRepository'] = new \App\Repository\DistributeurRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
