<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLbk3N42\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLbk3N42/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLbk3N42.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLbk3N42\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLbk3N42\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lbk3N42',
    'container.build_id' => 'c1055c7b',
    'container.build_time' => 1624434129,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLbk3N42');
